runtime: go112

default_expiration: "1m"

handlers:
- url: /
  static_files: root.html
  upload: root.html
  secure: always
- url: /serviceworker.js
  static_files: serviceworker.js
  upload: serviceworker.js
  secure: always
- url: /static
  static_dir: static
  secure: always
- url: /.*
  script: auto
  secure: always
